[package]
name = "bondrewd"
version = "0.1.4"
edition = "2021"
description = "Bit-Level field packing with proc_macros"
authors = ["Dev <devlynknelson@gmail.com>"]
license = "MIT OR Apache-2.0"
keywords = ["bitfields", "packed-struct", "bit-compression", "packed-fields", "packing"]
categories = ["compression","data-structures","development-tools"]
readme = "../README.md"
repository = "https://github.com/Devlyn-Nelson/Bondrewd"

[dependencies]
bondrewd-derive = { path = "../bondrewd-derive", optional = true }
thiserror = { version = "^1.0", optional = true }

[features] 
default = ["hex_fns"]
derive = ["bondrewd-derive"]
slice_fns = ["bondrewd-derive/slice_fns"]
hex_fns = ["bondrewd-derive/hex_fns"]