[package]
name = "bondrewd-derive"
version = "0.3.29"
edition = "2021"
description = "Bit-Level field packing with proc_macros"
authors = ["Dev <devlynknelson@gmail.com>"]
license = "MIT OR Apache-2.0"
keywords = ["bitfields", "packed-struct", "bit-compression", "packed-fields", "packing"]
# categories = ["compression","data-structures","development-tools"]
readme = "../README.md"
repository = "https://github.com/Devlyn-Nelson/Bondrewd"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "^1.0"
quote = "^1.0"
syn = "^1.0"
convert_case = "^0.6"

[features]
default = ["part_eq_enums"]
dyn_fns = []
hex_fns = []
part_eq_enums = []
# the setters feature is considered a nice to have and because chars are currently making this not work we are leaving its commented out
# setters = []

[dev-dependencies]
anyhow = "1.0.51"
bondrewd = { path = "../bondrewd", features = ["derive", "dyn_fns", "hex_fns"] }