[package]
name = "bondrewd-derive"
version = "0.4.2-pre0.5-1"
edition = "2021"
description = "Bit-Level field packing with proc_macros"
authors = ["Dev <devlynknelson@gmail.com>"]
license = "MIT OR Apache-2.0"
keywords = ["bitfields", "packed-struct", "bit-compression", "packed-fields", "packing"]
# categories = ["compression","data-structures","development-tools"]
readme = "../README.md"
repository = "https://github.com/Devlyn-Nelson/Bondrewd"

[lib]
proc-macro = true

[dependencies]
convert_case = "0.6"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["parsing", "derive"] }

[features]
# default = ["setters"]
dyn_fns = []
hex_fns = []
part_eq_enums = []
setters = []

[dev-dependencies]
rand = "0.8"
anyhow = "1.0.51"
bondrewd = { path = "../bondrewd", features = ["derive", "dyn_fns", "hex_fns"] }